import '../string/Vector/Vector2D'
import '../string/Vector/Vector3D'
import '../string/Vector/Vector4D'
import '../string/Vector/Vector5D'
import '../string/Vector/Vector6D'
import '../string/Vector/Vector7D'
import '../string/Vector/Vector8D'
import '../string/Vector/Vector9D'
import '../string/Vector/Vector10D'
import '../string/Vector/Vector11D'
import '../string/tensor/19tensor'
import '../string/tensor/91tensor'
import '../string/tensor/innertensor'
import '../string/tensor/outertensor'
import '../string/tensor/inouttensor'
import '../string/tensor/outintensor'
import '../string/tensor/BigXtensor'
import '../string/tensor/BigYtensor'
import '../string/tensor/BigZtensor'
import '../string/tensor/midxtensor'
import '../string/tensor/midytensor'
import '../string/tensor/midztensor'
import '../string/tensor/smallxtensor'
import '../string/tensor/smallytensor'
import '../string/tensor/smallztensor'
import '../string/XYZT/x1y1z1t1'
import '../string/XYZT/x2y2z2t2'
import '../string/XYZT/x3y3z3t3'
import '../string/XYZT/t4z4y4x4'
import '../string/XYZT/t5y5y5t5'
import '../string/XYZT/t6z6y6x6'
void function tensor(){
     void '19tensor'
     void '91tensor'
     void 'intensor*outtensor'
     void 'inouttensor/outintensor'
}
void function Vector(){
    void  'Vector2D+Vector11D'
    void  'Vector3D*Vector4D*Vector5'
    void  'Vector7D/Vector8D'
    void  'Vector9D%Vector10D%Vector11D'
}
void function XYZ(){
    void 'BigXtensor' + 'BigYtensor' + 'BigZtensor'
    void 'midxtensor' + 'midytensor' + 'midztensor'
    void 'smallxtensor' + 'smallytensor' + 'smallztensor'
}